echo results

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -38,26 +38,26 @@ jobs:
           echo "$unchangedFound"
           echo "$successFound"
 
-          if [ $errorFound ]
-          then
-            echo "Error found in log file"
-            echo "::error::Problems found when trying to publish packages"
-            exit 1
-          elif [ $unchangedFound && !$errorFound && !$successFound ]
-          then
-            echo "No changes found in log file"
-            echo "::warning::Nothing changed, you probably need to update your packages' versions"
-            exit 0
-          elif [ $successFound && !$errorFound && !$unchangedFound ]
-          then
-            echo "Success found in log file"
-            echo "::notice::Publishing was successful"
-            exit 0
-          else
-            echo "Some of your packages' versions probably need to be updated"
-            echo "::warning::You probably need to update some of your packages' versions"
-            exit 0
-          fi
+#          if [ $errorFound ]
+#          then
+#            echo "Error found in log file"
+#            echo "::error::Problems found when trying to publish packages"
+#            exit 1
+#          elif [ $unchangedFound && !$errorFound && !$successFound ]
+#          then
+#            echo "No changes found in log file"
+#            echo "::warning::Nothing changed, you probably need to update your packages' versions"
+#            exit 0
+#          elif [ $successFound && !$errorFound && !$unchangedFound ]
+#          then
+#            echo "Success found in log file"
+#            echo "::notice::Publishing was successful"
+#            exit 0
+#          else
+#            echo "Some of your packages' versions probably need to be updated"
+#            echo "::warning::You probably need to update some of your packages' versions"
+#            exit 0
+#          fi
 
 
 
